// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fahkcsmtvinkjwwnoxmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhaGtjc210dmlua2p3d25veG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MjEwNTAsImV4cCI6MjA1NTA5NzA1MH0.MeQqYRQn91ml8maLCokdOu68BRvAyFo5MvIS08YJPpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);